export default function ClimateSmart() {
  return (
    <section className="py-24 px-6 max-w-7xl mx-auto bg-bg-light dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors">
      <div className="grid md:grid-cols-2 gap-12 items-center">

        <div>
          <span className="text-brand-green font-bold uppercase tracking-widest text-sm">
            Environmental Impact
          </span>
          <h2 className="text-5xl font-black text-gray-900 dark:text-white mt-2 mb-6">
            Climate-Smart by Design
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Every recommendation generated by our AI is optimized for high
            yield while minimizing resource depletion and maximizing carbon
            sequestration credits.
          </p>
        </div>

        <div>
          <div className="flex items-center gap-2 mb-4">
            <span className="text-xs font-semibold bg-blue-50 text-blue-600 px-3 py-1 rounded-full border border-blue-100">
              🎯 Projected Targets
            </span>
            <span className="text-xs text-gray-400 dark:text-gray-500">
              Based on pilot simulations — not yet measured at scale
            </span>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {[
              { label: "Water Efficiency", val: "38%", desc: "Reduction in consumption" },
              { label: "Carbon Offset", val: "1.8t", desc: "Annual metric tons/farm" },
              { label: "Soil Health", val: "94%", desc: "Nutrient index stability" },
              { label: "Input Savings", val: "22%", desc: "Reduced fertilizer usage" }
            ].map((item, i) => (
              <div key={i} className="bg-white dark:bg-gray-800 p-6 rounded-3xl border border-gray-100 dark:border-gray-700 shadow-sm transition-colors">
                <div className="text-3xl font-black text-brand-green mb-1">
                  {item.val}
                </div>
                <div className="font-bold text-gray-900 dark:text-white">{item.label}</div>
                <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">{item.desc}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  );
}
